/* Service worker – offline support. VERSION and PRECACHE are (re)generated by tools/build_sw.py. */
const VERSION = '211e8c2b48';
const PRECACHE = ["./", "index.html", "manifest.webmanifest", "css/style.css", "js/app.js", "js/badges.js", "js/charts.js", "js/config.js", "js/ctx.js", "js/data.js", "js/fx.js", "js/progress.js", "js/quiz.js", "js/readiness.js", "js/session.js", "js/store.js", "js/ui.js", "js/views/browse.js", "js/views/exam.js", "js/views/home.js", "js/views/learn.js", "js/views/onboarding.js", "js/views/practice.js", "js/views/review.js", "js/views/search.js", "js/views/settings.js", "js/views/signs.js", "js/views/stats.js", "fonts/rubik-hebrew.woff2", "fonts/rubik-latin.woff2", "data/questions.json", "data/units.json", "img/app/icon-180.png", "img/app/icon-192.png", "img/app/icon-512.png", "img/app/icon-maskable-512.png", "img/app/icon.svg", "img/units/safety-curves-hills.svg", "img/units/safety-driver-state.svg", "img/units/safety-junction-overtake.svg", "img/units/safety-park-reverse.svg", "img/units/safety-people.svg", "img/units/safety-speed-gap.svg", "img/units/safety-start.svg", "img/units/safety-weather-night.svg", "img/units/signs-basics.svg", "img/units/signs-direction.svg", "img/units/signs-junctions.svg", "img/units/signs-lights.svg", "img/units/signs-priority.svg", "img/units/signs-prohibitions.svg", "img/units/signs-roads-info.svg", "img/units/signs-warning-roadworks.svg"];
const IMG_CACHE = 'road26-img-v1';
const APP_CACHE = `road26-app-${VERSION}`;

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(APP_CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil((async () => {
    for (const k of await caches.keys()) if (k.startsWith('road26-app-') && k !== APP_CACHE) await caches.delete(k);
    await self.clients.claim();
  })());
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // Question pictures: cache-first, filled lazily (or all at once from Settings).
  if (url.pathname.includes('/img/q/')) {
    e.respondWith((async () => {
      const c = await caches.open(IMG_CACHE);
      const hit = await c.match(req);
      if (hit) return hit;
      try { const r = await fetch(req); if (r.ok) c.put(req, r.clone()); return r; }
      catch (err) { return new Response('', { status: 504 }); }
    })());
    return;
  }

  // App shell: stale-while-revalidate keeps it instant offline and picks up updates on the next load.
  e.respondWith((async () => {
    const c = await caches.open(APP_CACHE);
    const hit = await c.match(req, { ignoreSearch: true });
    const net = fetch(req).then((r) => { if (r.ok) c.put(req, r.clone()); return r; }).catch(() => null);
    if (hit) { e.waitUntil(net); return hit; }
    const r = await net;
    if (r) return r;
    if (req.mode === 'navigate') { const idx = await c.match('./'); if (idx) return idx; }
    return new Response('offline', { status: 503 });
  })());
});
